# Generated by Django 4.0.2 on 2022-02-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordAccount',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=72)),
                ('password', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
