# Generated by Django 4.0.2 on 2022-02-18 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail_account', '0001_initial'),
        ('discord_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordaccount',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mail_account.mailaccount'),
        ),
    ]
