# Generated by Django 4.0.2 on 2022-02-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=46)),
                ('password', models.CharField(max_length=32)),
                ('secret_answer', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
